### ISSUE TITLE
Wall Placement Errors (Especially with Décor Walls or Pillars)

### ISSUE THREAD

**Issue by Kjegla** [sakura-ryoko/litematica-printer#9]
Issue: Wall Placement Errors (Especially with Décor Walls or Pillars)

It seems the printer is encountering issues with the placement of walls, particularly when dealing with décor walls that are intended to hang or serve as pillars.

For example, when trying to print a 3x3 wall, the printer fails to print any of the wall blocks. Occasionally, placing the top row may allow the wall to continue being printed down one level (yet not all the way down, or to the side), but this behavior is inconsistent. Overall, the printing process does not behave reliably, and the results are unpredictable :( 

Got any ideas to what could cause this?

**Comment by sakura-ryoko** [comment]
The printer is often limited to blocks that are adjacent to existing blocks.  Also, This repo is now in the "post-sakura" era, since the 1.21.3+ versions have been merged with the upstream repo.

**Comment by Kjegla** [comment]
I see! Thx :)
